### ISSUE TITLE
No module named core

### ISSUE THREAD

**Issue by LiminalD** [ronanren/CryptoTickerLed#1]
Hi Ronan,

I really like this project, keep up the good work!

My config:
Raspberry Pi 4b
Latest version of Raspberry Pi OS 64bit, Debian Bookworm (If I use your suggestion for OS (dietpi), I run into exactly the same issue) Python 2.7 installed.
Adafruit RGB Matrix Bonnet

I am stuck on the following, can you help me further?

root@DietPi:~/CryptoTickerLed/project# sudo ./run.py --led-gpio-mapping=adafruit-hat --led-rows=32 --led-cols=64 --led-slowdown-gpio=4Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from samplebase import SampleBase
  File "/root/CryptoTickerLed/project/samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "/root/CryptoTickerLed/project/rgbmatrix/__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
ImportError: No module named core

Below some logs with errors during install:

root@raspberrypi:/home/pi/CryptoTickerLed/matrix# sudo make install-python
make -C ./lib
make[1]: Entering directory '/home/pi/CryptoTickerLed/matrix/lib'
make[1]: Leaving directory '/home/pi/CryptoTickerLed/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/CryptoTickerLed/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/pi/CryptoTickerLed/matrix/lib'
make[2]: Leaving directory '/home/pi/CryptoTickerLed/matrix/lib'
make[1]: Leaving directory '/home/pi/CryptoTickerLed/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/CryptoTickerLed/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/CryptoTickerLed/matrix/lib'
make[2]: Leaving directory '/home/pi/CryptoTickerLed/matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
make[1]: Leaving directory '/home/pi/CryptoTickerLed/matrix/bindings/python'
make -C bindings/python install
make[1]: Entering directory '/home/pi/CryptoTickerLed/matrix/bindings/python'
python setup.py install
running install
running build
running build_py
creating build/lib.linux-aarch64-2.7
creating build/lib.linux-aarch64-2.7/rgbmatrix
copying rgbmatrix/__init__.py -> build/lib.linux-aarch64-2.7/rgbmatrix
running build_ext
building 'core' extension
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/core.cpp -o build/temp.linux-aarch64-2.7/rgbmatrix/core.o -O3 -Wall
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/python2.7/Python.h:88,
                 from rgbmatrix/core.cpp:6:
/usr/include/python2.7/unicodeobject.h:534:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  534 |     register PyObject *obj,     /* Object */
      |                        ^~~
/usr/include/python2.7/unicodeobject.h:553:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  553 |     register PyObject *obj      /* Object */
      |                        ^~~
/usr/include/python2.7/unicodeobject.h:575:29: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  575 |     register const wchar_t *w,  /* wchar_t buffer */
      |                             ^
/usr/include/python2.7/unicodeobject.h:593:23: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  593 |     register wchar_t *w,        /* wchar_t buffer */
      |                       ^
In file included from /usr/include/python2.7/Python.h:97:
/usr/include/python2.7/stringobject.h:173:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  173 |     register PyObject *obj,     /* string or Unicode object */
      |                        ^~~
/usr/include/python2.7/stringobject.h:174:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  174 |     register char **s,          /* pointer to buffer variable */
      |                     ^
/usr/include/python2.7/stringobject.h:175:26: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  175 |     register Py_ssize_t *len    /* pointer to length variable or NULL
      |                          ^~~
aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-aarch64-2.7/rgbmatrix/core.o -L../../lib -lrgbmatrix -o build/lib.linux-aarch64-2.7/rgbmatrix/core.so
building 'graphics' extension
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/graphics.cpp -o build/temp.linux-aarch64-2.7/rgbmatrix/graphics.o -O3 -Wall
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/python2.7/Python.h:88,
                 from rgbmatrix/graphics.cpp:6:
/usr/include/python2.7/unicodeobject.h:534:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  534 |     register PyObject *obj,     /* Object */
      |                        ^~~
/usr/include/python2.7/unicodeobject.h:553:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  553 |     register PyObject *obj      /* Object */
      |                        ^~~
/usr/include/python2.7/unicodeobject.h:575:29: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  575 |     register const wchar_t *w,  /* wchar_t buffer */
      |                             ^
/usr/include/python2.7/unicodeobject.h:593:23: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  593 |     register wchar_t *w,        /* wchar_t buffer */
      |                       ^
In file included from /usr/include/python2.7/Python.h:97:
/usr/include/python2.7/stringobject.h:173:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  173 |     register PyObject *obj,     /* string or Unicode object */
      |                        ^~~
/usr/include/python2.7/stringobject.h:174:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  174 |     register char **s,          /* pointer to buffer variable */
      |                     ^
/usr/include/python2.7/stringobject.h:175:26: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  175 |     register Py_ssize_t *len    /* pointer to length variable or NULL
      |                          ^~~
aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-aarch64-2.7/rgbmatrix/graphics.o -L../../lib -lrgbmatrix -o build/lib.linux-aarch64-2.7/rgbmatrix/graphics.so
running install_lib
creating /usr/local/lib/python2.7/dist-packages/rgbmatrix
copying build/lib.linux-aarch64-2.7/rgbmatrix/__init__.py -> /usr/local/lib/python2.7/dist-packages/rgbmatrix
copying build/lib.linux-aarch64-2.7/rgbmatrix/graphics.so -> /usr/local/lib/python2.7/dist-packages/rgbmatrix
copying build/lib.linux-aarch64-2.7/rgbmatrix/core.so -> /usr/local/lib/python2.7/dist-packages/rgbmatrix
byte-compiling /usr/local/lib/python2.7/dist-packages/rgbmatrix/__init__.py to __init__.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/rgbmatrix-0.0.1.egg-info
make[1]: Leaving directory '/home/pi/CryptoTickerLed/matrix/bindings/python'

**Comment by LiminalD** [comment]
Hi Ronan,

I have found that the issue has to do with the paths see below the error, can you help me out with setting the correct references?

root@raspberrypi:/home/pi/CryptoTickerLed/project# ./run.py --led-gpio-mapping=adafruit-hat --led-rows=32 --led-cols=64 —led-slowdown-gpio=4
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from samplebase import SampleBase
  File "/home/pi/CryptoTickerLed/project/samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "/home/pi/CryptoTickerLed/project/rgbmatrix/__init__.py", line 7, in <module>
ImportError: No module named core

**Comment by ronanren** [comment]
Hi, 

have you installed the various steps as shown in the readme? https://github.com/ronanren/CryptoTickerLed?tab=readme-ov-file#software

Else, do you run the script in sudo ? it's important according to the documentation of the library.

To finish, It's maybe an issue about this line of code that doesn't fit with your setup : sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/..')) line 6 in project/samplebase.py

**Comment by LiminalD** [comment]
Hi Ronan, I do everything as sudo however I have raspberry pi os running 64 bit bookworm maybe this is not compatible? Met vriendelijke groet, With kind regards, Steven de Boer  From: Ronan ***@***.***>Date: Sunday, 17 December 2023 at 15:11To: ronanren/CryptoTickerLed ***@***.***>Cc: LiminalD ***@***.***>, Author ***@***.***>Subject: Re: [ronanren/CryptoTickerLed] No module named core (Issue #1)Hi,have you installed the various steps as shown in the readme? https://github.com/ronanren/CryptoTickerLed?tab=readme-ov-file#softwareElse, do you run the script in sudo ? it's important according to the documentation of the library.To finish, It's maybe an issue about this line of code that doesn't fit with your setup : sys.path.append(os.path.abspath(os.path.dirname(file) + '/..')) line 6 in project/samplebase.py—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ronanren** [comment]
Yes it's maybe not compatible with your os, try with DietPi.
